apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: webapp

resources:
  # Namespace
  - namespace.yaml

  # Frontend
  - frontend/configmap.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - frontend/hpa.yaml

  # Backend
  - backend/configmap.yaml
  - backend/secret.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - backend/hpa.yaml

  # Ingress
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: webapp
  app.kubernetes.io/managed-by: kustomize
